name: Notify on Issue
on:
  issues: 
    types: [opened]

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps: 
      - name: Google Chat Message
        run: |
          curl -X POST -H 'Content-type: application/json; charset=UTF-8'
           -- data '{"text":"New issue created: <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}.>"}' 
           ${{ secrets.GOOGLE_CHAT_WEBHOOK }}